# Generated by Django 4.2.24 on 2026-03-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="owners",
            field=models.ManyToManyField(
                blank=True,
                related_name="assets",
                through="lineage.AssetOwnership",
                to="lineage.person",
            ),
        ),
    ]
