# Generated by Django 5.1.1 on 2026-02-05 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0002_assetcategory_alter_asset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
