# Generated by Django 5.1.1 on 2026-02-06 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0003_children_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
