# Generated by Django 5.1.1 on 2026-02-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0005_children_user_parents_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
        ),
    ]
