# Generated by Django 4.2.24 on 2026-02-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0006_children_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='user',
        ),
        migrations.DeleteModel(
            name='Children',
        ),
        migrations.DeleteModel(
            name='Parents',
        ),
    ]
