# Generated by Django 4.2.24 on 2026-02-24 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lineage", "0007_remove_parents_parent_remove_parents_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share",
                    models.DecimalField(
                        decimal_places=2, help_text="Ownership percentage", max_digits=5
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("alive", "Alive"), ("deceased", "Deceased")],
                        default="alive",
                        max_length=20,
                    ),
                ),
                (
                    "job_status",
                    models.CharField(
                        choices=[
                            ("employed", "Employed"),
                            ("unemployed", "Unemployed"),
                        ],
                        default="unemployed",
                        max_length=20,
                    ),
                ),
                (
                    "disability_status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("physical", "Physical"),
                            ("mental", "Mental"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="members/"),
                ),
                (
                    "father",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children_from_father",
                        to="lineage.person",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children_from_mother",
                        to="lineage.person",
                    ),
                ),
                (
                    "spouse",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="married_to",
                        to="lineage.person",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="owner",
            name="asset",
        ),
        migrations.RenameField(
            model_name="contribution",
            old_name="created_at",
            new_name="contributed_at",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="category",
        ),
        migrations.RemoveField(
            model_name="contribution",
            name="family",
        ),
        migrations.RemoveField(
            model_name="contribution",
            name="member_name",
        ),
        migrations.AddField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[("D", "Dispute"), ("O", "Owned")], default="O", max_length=20
            ),
        ),
        migrations.DeleteModel(
            name="AssetCategory",
        ),
        migrations.DeleteModel(
            name="Family",
        ),
        migrations.DeleteModel(
            name="Owner",
        ),
        migrations.AddField(
            model_name="assetownership",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownerships",
                to="lineage.asset",
            ),
        ),
        migrations.AddField(
            model_name="assetownership",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lineage.person"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="owners",
            field=models.ForeignKey(
                default="simon",
                on_delete=django.db.models.deletion.CASCADE,
                to="lineage.person",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contribution",
            name="member",
            field=models.ForeignKey(
                default="simon",
                on_delete=django.db.models.deletion.CASCADE,
                to="lineage.person",
            ),
            preserve_default=False,
        ),
    ]
