# Generated by Django 4.2.24 on 2026-02-24 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lineage", "0008_assetownership_person_remove_owner_asset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lineage.person",
            ),
        ),
    ]
